### ISSUE TITLE
upgrade to 1.3 breaks cpo200 lab

### ISSUE THREAD

**Issue by marcokammerer** [GoogleCloudPlatformTraining/cpo200-startup-scripts#1]
The updates to version 1.3 in cpo200-startup-scripts/guestbook-start.sh break the lab https://codelabs.developers.google.com/codelabs/cpo200-startup-scripts/#4

The old version was directly connecting to the Google Cloud SQL instance by reading the IP of the Cloud SQL instance from the metadata attributes/sql-ip.
The new version tries to read from the attributes/sql-connection-name which does not exist in the lab https://codelabs.developers.google.com/codelabs/cpo200-startup-scripts/#4 at this point.

Additionally the last line does not look right. It looks like that the beginning of the command was truncated by error while editing.

Reverting back to < 1.3 fixes https://codelabs.developers.google.com/codelabs/cpo200-startup-scripts/#4

**Comment by oclipa** [comment]
Since this hasn't been actioned yet, can I just a "me too!" to this.  I just spent a frustrating afternoon trying to get past step 7.  This really needs to be fixed as it demotivating thinking you've done something wrong, only for it to turn out that the lab is unreliable...

**Comment by tomgcp** [comment]
Replaced the last line of the guestbook-start.sh script from /proxy/... to ./
